/**
 * Type of messages exchanged between chat client and server
 */
export enum ChatEventType {
  /**
   * Client to Server
   */
  // authentication request sent from client to server
  CLIENT_AUTH_REQUEST = 'CLIENT_AUTH_REQUEST',
  // chat message sent from client to server
  CLIENT_MESSAGE = 'CLIENT_MESSAGE',

  /**
   * Server to Client
   */
  // success response for any request
  CLIENT_REQUEST_SUCCESS = 'CLIENT_REQUEST_SUCCESS',
  // error response for any client request
  CLIENT_REQUEST_ERROR = 'CLIENT_REQUEST_ERROR',

  // #TODO below
  // chat message sent from server to client(s) (usually via broadcast)
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  // chat history sent from server to client
  CHAT_HISTORY = 'CHAT_HISTORY',
  // message sent from server to client(s) to inform about a new participant (usually via broadcast)
  NEW_PARTICIPANT = 'NEW_PARTICIPANT',
  // message sent from server to client(s) to inform about a leaving participant (usually via broadcast)
  LEAVING_PARTICIPANT = 'LEAVING_PARTICIPANT'
}

/**
 * Message exchanged between chat client and server
 */
export interface ChatEvent {
  // event type
  type: ChatEventType;
  // event payload
  body: any;
  // transaction ID generated by the client
  transactionId: string;
}
